/**
 * Per-station traffic statistics (Phase 30A, PLAYTEST-2 "missing 2"): revenue generated by cargo loaded
 * at a station, and passengers / mail that gave up waiting there ("turned away") with an estimate of
 * the fares lost. The UI (Phase 30B) reads `state.stationFlow`; nothing in the sim depends on it.
 *
 * Periods: `month` / `year` accumulate; `lastMonth` / `lastYear` hold the previous completed period.
 */
import { CARGO, type CargoType } from "../../data/cargo";
import type { GameState } from "../state";
import { computeRevenue } from "../trains/loading";

export interface CargoFlow {
  /** Fares earned by cargo that was loaded at this station (credited when it is delivered). */
  revenue: number;
  /** Units of that cargo. */
  units: number;
  /** Passengers / mail bags that gave up waiting here. */
  lostUnits: number;
  /** Estimated fares those people would have paid (`lostUnits` × the recent fare per unit here). */
  lostRevenue: number;
  /** Units loaded onto trains here (counted at loading, so a long trip still shows before it is paid). */
  sent?: number;
  /** Units of this cargo delivered (unloaded for pay) at this station. */
  delivered?: number;
  /** Fares paid for the cargo delivered here. */
  deliveredRevenue?: number;
}

export type FlowPeriod = Partial<Record<CargoType, CargoFlow>>;

export interface StationFlow {
  month: FlowPeriod;
  lastMonth: FlowPeriod;
  year: FlowPeriod;
  lastYear: FlowPeriod;
  /** Smoothed fare per unit of cargo loaded here (EMA of delivered revenue ÷ units). */
  fare: Partial<Record<CargoType, number>>;
}

export function emptyStationFlow(): StationFlow {
  return { month: {}, lastMonth: {}, year: {}, lastYear: {}, fare: {} };
}

export function getStationFlow(state: GameState, stationId: number): StationFlow {
  let flow = state.stationFlow.get(stationId);
  if (!flow) {
    flow = emptyStationFlow();
    state.stationFlow.set(stationId, flow);
  }
  return flow;
}

function bucket(period: FlowPeriod, cargo: CargoType): CargoFlow {
  return (period[cargo] ??= { revenue: 0, units: 0, lostUnits: 0, lostRevenue: 0 });
}

/** Fare per unit when no delivery from this station has been seen yet: a 60 km trip at the era's fare. */
function nominalFare(state: GameState, cargo: CargoType): number {
  return computeRevenue(state, cargo, 12, 4) / CARGO[cargo].capacity;
}

export function recordLoadedRevenue(
  state: GameState,
  stationId: number,
  cargo: CargoType,
  units: number,
  revenue: number,
): void {
  if (units <= 0) return;
  const flow = getStationFlow(state, stationId);
  for (const period of [flow.month, flow.year]) {
    const b = bucket(period, cargo);
    b.revenue += revenue;
    b.units += units;
  }
  const perUnit = revenue / units;
  const prev = flow.fare[cargo];
  flow.fare[cargo] = prev === undefined ? perUnit : prev * 0.7 + perUnit * 0.3;
}

export function recordSent(
  state: GameState,
  stationId: number,
  cargo: CargoType,
  units: number,
): void {
  if (units <= 0) return;
  const flow = getStationFlow(state, stationId);
  for (const period of [flow.month, flow.year]) {
    const b = bucket(period, cargo);
    b.sent = (b.sent ?? 0) + units;
  }
}

export function recordDelivered(
  state: GameState,
  stationId: number,
  cargo: CargoType,
  units: number,
  revenue: number,
): void {
  if (units <= 0) return;
  const flow = getStationFlow(state, stationId);
  for (const period of [flow.month, flow.year]) {
    const b = bucket(period, cargo);
    b.delivered = (b.delivered ?? 0) + units;
    b.deliveredRevenue = (b.deliveredRevenue ?? 0) + revenue;
  }
}

export function recordTurnedAway(
  state: GameState,
  stationId: number,
  cargo: CargoType,
  units: number,
): void {
  if (units <= 0) return;
  const flow = getStationFlow(state, stationId);
  const fare = flow.fare[cargo] ?? nominalFare(state, cargo);
  for (const period of [flow.month, flow.year]) {
    const b = bucket(period, cargo);
    b.lostUnits += units;
    b.lostRevenue += units * fare;
  }
}

export function monthlyStationFlowRollover(state: GameState): void {
  for (const flow of state.stationFlow.values()) {
    flow.lastMonth = flow.month;
    flow.month = {};
  }
}

export function yearlyStationFlowRollover(state: GameState): void {
  for (const flow of state.stationFlow.values()) {
    flow.lastYear = flow.year;
    flow.year = {};
  }
}

/** Sum over cargo types of a period's lost revenue (for a headline "turned away" figure). */
export function totalLostRevenue(period: FlowPeriod): number {
  let total = 0;
  for (const b of Object.values(period)) total += b?.lostRevenue ?? 0;
  return total;
}
