/** All user-facing strings live here (CLAUDE.md hard rule), including dev-only debug UI. */
export const strings = {
  app: {
    exitGameConfirm: "Exit game?",
  },
  ui: {
    close: "Close",
  },
  topBar: {
    pause: "Pause",
    menu: "Menu",
  },
  toolbar: {
    track: "Track",
    double: "Double",
    electrify: "Electrify",
    station: "Station",
    bulldoze: "Bulldoze",
    info: "Info",
  },
  city: {
    population: "Population",
    tier: "Tier",
    tierNames: {
      village: "Village",
      town: "Town",
      city: "City",
      metropolis: "Metropolis",
    },
  },
  industry: {
    produces: "Produces",
    consumes: "Consumes",
    perMonth: "/mo",
    availableFrom: "Available from",
  },
  build: {
    reasons: {
      "no-path": "Drag to draw a path first",
      blocked: "No valid route or bridge there",
      "cant-afford": "Not enough cash",
      "no-track-to-upgrade": "No single track to upgrade there",
      "nothing-to-bulldoze": "No track there to bulldoze",
      "station-no-track": "Needs a straight or dead-end track tile",
      "station-occupied": "There's already a station there",
      "invalid-station-upgrade": "Can't upgrade to that type",
      "invalid-station-name": "Enter a name",
      "no-engine-shed": "This station has no Engine Shed",
      "invalid-locomotive": "That locomotive isn't available",
      "too-many-cars": "Too many cars for that locomotive",
      "invalid-train": "That train doesn't exist",
      "invalid-orders": "Orders need 2-8 valid stations",
    },
    confirmBuild: "Build",
    confirmUpgrade: "Upgrade",
    confirmBulldoze: "Bulldoze",
    cancel: "✕",
    bridgeWood: "Wood bridge",
    bridgeStone: "Stone bridge",
    bridgeSteel: "Steel bridge",
    tapToChangeBridge: "Tap to change bridge type",
    quickBuild: "Quick build",
  },
  station: {
    types: {
      depot: "Depot",
      station: "Station",
      terminal: "Terminal",
    },
    newStationTitle: "New Station",
    type: "Type",
    tapTrackTile: "Tap a straight or dead-end track tile to place a station",
    catchment: "Catchment",
    maxTrainLength: "Max train length",
    storagePerCargo: "Storage/cargo",
    monthlyMaintenance: "Maintenance",
    perMonth: "/mo",
    supplies: "Supplies (per month)",
    accepts: "Accepts (points, ≥8 unlocks)",
    waitingCargo: "Waiting cargo",
    waitingCargoPlaceholder: "Cargo flow arrives in a later phase.",
    engineShedFree: "Free Engine Shed",
    rename: "Name",
    upgradeToPrefix: "Upgrade to ",
    build: "Build",
    cancel: "✕",
  },
  trains: {
    buyTitle: "Buy Train",
    locomotive: "Locomotive",
    cars: "Cars",
    orders: "Orders",
    buy: "Buy",
    sell: "Sell",
    status: "Status",
    speed: "Speed",
    consist: "Consist",
    none: "No trains yet.",
    listTitle: "Trains",
    addStop: "+ Add stop (tap a station)",
    tapAStation: "Tap a station on the map…",
    trainsButton: "Trains",
    locoTypes: {
      steam: "Steam",
      diesel: "Diesel",
      electric: "Electric",
    },
    statusNames: {
      loading: "Loading",
      moving: "Moving",
      waitingForBlock: "Waiting (block)",
      waitingForStation: "Waiting (station)",
      noRoute: "No route ⚠",
      stuck: "Stuck ⚠",
    },
    loadingRules: {
      auto: "Auto",
      fullLoad: "Full load",
      unloadOnly: "Unload only",
      passThrough: "Pass through",
    },
    trafficJam: (name: string) =>
      `Traffic jam near ${name} — consider double track or more stations`,
  },
  debug: {
    regenerate: "New seed",
    seedLabel: "Seed",
    sizeLabel: "Size",
    sizeSmall: "Small",
    sizeMedium: "Medium",
    sizeLarge: "Large",
  },
};
