/** All user-facing strings live here (CLAUDE.md hard rule), including dev-only debug UI. */
export const strings = {
  app: {
    exitGameConfirm: "Exit game?",
  },
  ui: {
    close: "Close",
  },
  topBar: {
    pause: "Pause",
    menu: "Menu",
  },
  toolbar: {
    track: "Track",
    double: "Double",
    electrify: "Electrify",
    station: "Station",
    bulldoze: "Bulldoze",
    info: "Info",
  },
  city: {
    population: "Population",
    tier: "Tier",
    tierNames: {
      village: "Village",
      town: "Town",
      city: "City",
      metropolis: "Metropolis",
    },
  },
  industry: {
    produces: "Produces",
    consumes: "Consumes",
    perMonth: "/mo",
    availableFrom: "Available from",
  },
  build: {
    reasons: {
      "no-path": "Drag to draw a path first",
      blocked: "No valid route or bridge there",
      "cant-afford": "Not enough cash",
      "no-track-to-upgrade": "No single track to upgrade there",
      "not-era-available": "Not available yet",
      "already-improved": "Already built here",
      "nothing-to-bulldoze": "No track there to bulldoze",
      "station-no-track": "Needs a straight or dead-end track tile",
      "station-occupied": "There's already a station there",
      "invalid-station-upgrade": "Can't upgrade to that type",
      "invalid-station-name": "Enter a name",
      "no-engine-shed": "This station has no Engine Shed",
      "invalid-locomotive": "That locomotive isn't available",
      "steam-phased-out": "Steam locomotives can't be bought after 1960",
      "too-many-cars": "Too many cars for that locomotive",
      "invalid-train": "That train doesn't exist",
      "invalid-orders": "Orders need 2-8 valid stations",
      "invalid-loan-amount": "Amount must be a multiple of $100k",
      "credit-limit-exceeded": "That would exceed your credit limit",
    },
    confirmBuild: "Build",
    confirmUpgrade: "Upgrade",
    confirmElectrify: "Electrify",
    confirmBulldoze: "Bulldoze",
    cancel: "✕",
    bridgeWood: "Wood bridge",
    bridgeStone: "Stone bridge",
    bridgeSteel: "Steel bridge",
    tapToChangeBridge: "Tap to change bridge type",
    quickBuild: "Quick build",
  },
  station: {
    types: {
      depot: "Depot",
      station: "Station",
      terminal: "Terminal",
    },
    newStationTitle: "New Station",
    type: "Type",
    tapTrackTile: "Tap a straight or dead-end track tile to place a station",
    catchment: "Catchment",
    maxTrainLength: "Max train length",
    storagePerCargo: "Storage/cargo",
    monthlyMaintenance: "Maintenance",
    perMonth: "/mo",
    supplies: "Supplies (per month)",
    accepts: "Accepts (points, ≥8 unlocks)",
    waitingCargo: "Waiting cargo",
    waitingCargoNone: "Nothing waiting.",
    engineShedFree: "Free Engine Shed",
    waterTowerBuilt: "Water Tower",
    buildWaterTower: "Build Water Tower",
    rename: "Name",
    upgradeToPrefix: "Upgrade to ",
    build: "Build",
    cancel: "✕",
  },
  trains: {
    buyTitle: "Buy Train",
    locomotive: "Locomotive",
    cars: "Cars",
    orders: "Orders",
    buy: "Buy",
    sell: "Sell",
    status: "Status",
    speed: "Speed",
    consist: "Consist",
    empty: "Empty",
    none: "No trains yet.",
    listTitle: "Trains",
    addStop: "+ Add stop (tap a station)",
    tapAStation: "Tap a station on the map…",
    trainsButton: "Trains",
    newBadge: "New!",
    locoTypes: {
      steam: "Steam",
      diesel: "Diesel",
      electric: "Electric",
    },
    statusNames: {
      loading: "Loading",
      moving: "Moving",
      waitingForBlock: "Waiting (block)",
      waitingForStation: "Waiting (station)",
      noRoute: "No route ⚠",
      stuck: "Stuck ⚠",
      broken: "Broken down 🔧",
    },
    loadingRules: {
      auto: "Auto",
      fullLoad: "Full load",
      unloadOnly: "Unload only",
      passThrough: "Pass through",
    },
    routeNotElectrified: "Route not electrified ⚡",
    replace: "Replace",
    replaceTitle: "Replace Locomotive",
    tradeInCredit: "Trade-in credit",
  },
  finance: {
    title: "Finance",
    cash: "Cash",
    loans: "Loans",
    creditLimit: "Credit limit",
    borrow: "Borrow $100k",
    repay: "Repay $100k",
    netWorth: "Net worth",
    thisYear: "This year",
    lastYear: "Last year",
    revenue: "Revenue",
    passengers: "Passengers",
    mail: "Mail",
    freight: "Freight",
    expenses: "Expenses",
    trainMaintenance: "Train maint.",
    trackMaintenance: "Track maint.",
    stationMaintenance: "Station maint.",
    breakdownRepairs: "Repairs",
    interest: "Interest",
    construction: "Construction",
    rollingStock: "Rolling stock",
    netProfit: "Net profit",
    chartTitle: "Cash & net worth",
    chartCash: "Cash",
    chartNetWorth: "Net worth",
    yearlyReport: "Yearly Report",
    bankruptWarning: "Cash has been negative for months — borrow, sell trains, or cut costs.",
  },
  yearlyReport: {
    title: (year: number) => `${year} Year in Review`,
    close: "Close",
    newTechnology: "New technology",
  },
  news: {
    title: "News",
    button: "News",
    empty: "No news yet.",
    kinds: {
      newLocomotive: (locoName: string) => `New locomotive available: ${locoName}`,
      breakdown: (trainName: string) => `${trainName} has broken down and is being repaired`,
      washout: (nearName: string) => `A wooden bridge near ${nearName} has washed out`,
      trafficJam: (nearName: string) =>
        `Traffic jam near ${nearName} — consider double track or more stations`,
      noRoute: (trainName: string, stationName: string) =>
        `${trainName} has no route to ${stationName}`,
    },
  },
  debug: {
    regenerate: "New seed",
    seedLabel: "Seed",
    sizeLabel: "Size",
    sizeSmall: "Small",
    sizeMedium: "Medium",
    sizeLarge: "Large",
  },
};
