/** All user-facing strings live here (CLAUDE.md hard rule), including dev-only debug UI. */
export const strings = {
  app: {
    exitGameConfirm: "Exit game?",
  },
  ui: {
    close: "Close",
    back: "Back",
    actions: "Actions",
    stats: "Stats",
    nothing: "Nothing yet",
  },
  topBar: {
    pause: "Pause",
    menu: "Menu",
    cash: "Finance",
    era: (name: string, year: number) => `Newest engine: ${name} (${year}) — open Roster`,
  },
  menu: {
    title: "Menu",
    game: "Game",
    saveGame: "Save Game",
    settings: "Settings",
    roster: "Roster",
    overlays: "Overlays",
    overlayNames: {
      catchments: "All catchments",
      cargoHeatmap: "Cargo supply heatmap",
      trackType: "Track type colors",
      trainProfit: "Train profit colors",
    },
    cargoHeatmapPrompt: "Cargo",
    miniMap: "Mini-map",
  },
  miniMap: {
    label: "Map",
  },
  toolbar: {
    track: "Track",
    double: "Double",
    electrify: "Electrify",
    station: "Station",
    bulldoze: "Bulldoze",
    info: "Info",
  },
  city: {
    tierNames: {
      village: "Village",
      town: "Town",
      city: "City",
      metropolis: "Metropolis",
    },
    growing: "Growing",
    stagnant: "Stagnant",
    civicInvestment: "Civic Investment",
    civicInvestmentDesc: "+15% population and an immediate growth tick",
    civicInvestmentCooldown: (years: number) => `Available again in ${years}y`,
    servedBy: "Served by",
    servedByNone: "No station nearby yet",
    noSupplies: "Nothing to ship",
    civicNeedsRail: "Needs a rail link",
    civicInvestmentShort: "+15% pop",
    noStationIn: (name: string) => `No station in ${name} yet`,
  },
  industry: {
    produces: "Produces",
    consumes: "Consumes",
    perMonth: "/mo",
    perMonthNote: "per month",
    availableFrom: "Available from",
    /** PLAN Phase 18 D: "Makes Goods from Steel or Lumber" / "Needs Coal and Iron ore". */
    makes: "Makes",
    makesFrom: "from",
    needs: "Needs",
    or: "or",
    and: "and",
    nearestSources: "Nearest sources",
    since: (year: number) => `Since ${year}`,
    kind: "Industry",
    recipeMakes: (outputs: string, inputs: string) => `Makes ${outputs} from ${inputs}`,
    recipeNeeds: (inputs: string) => `Needs ${inputs}`,
    recipeProduces: (outputs: string) => `Produces ${outputs}`,
    tilesAway: (n: number) => `${n} ${n === 1 ? "tile" : "tiles"}`,
    noSourceNearby: "None on the map yet",
    showOnMap: "Show on map",
  },
  build: {
    reasons: {
      "no-path": "Drag to draw a path first",
      blocked: "No valid route or bridge there",
      sharpTurn: "Too sharp — trains can't turn more than 45° here",
      "cant-afford": "Not enough cash",
      "no-track-to-upgrade": "No single track to upgrade there",
      "not-era-available": "Not available yet",
      "already-improved": "Already built here",
      "nothing-to-bulldoze": "No track there to bulldoze",
      "station-no-track": "Needs a straight or dead-end track tile",
      "station-occupied": "There's already a station there",
      "invalid-station-upgrade": "Can't upgrade to that type",
      "invalid-station-name": "Enter a name",
      "no-engine-shed": "This station has no Engine Shed",
      "invalid-locomotive": "That locomotive isn't available",
      "steam-phased-out": "Steam locomotives can't be bought after 1960",
      "too-many-cars": "Too many cars for that locomotive",
      "invalid-consist": "That consist isn't valid for this locomotive",
      "invalid-train": "That train doesn't exist",
      "invalid-orders": "Orders need 2-8 valid stations",
      "invalid-loan-amount": "Amount must be a multiple of $100k",
      "credit-limit-exceeded": "That would exceed your credit limit",
      "invalid-city": "That city doesn't exist",
      "city-not-connected": "Connect this city by rail first",
      "civic-investment-cooldown": "Civic Investment is on cooldown here",
    },
    confirmBuild: "Build",
    confirmUpgrade: "Upgrade",
    confirmElectrify: "Electrify",
    confirmBulldoze: "Bulldoze",
    bridgeWood: "Wood bridge",
    bridgeStone: "Stone bridge",
    bridgeSteel: "Steel bridge",
    tapToChangeBridge: "Tap to change bridge type",
    quickBuild: "Quick build",
  },
  station: {
    /** PLAN Phase 18 C: Warehouse transfer hub. */
    transferTitle: "Waiting for transfer",
    transferEmpty: "Warehouse: trains can leave any cargo here for another train to pick up",
    transferFrom: (cargo: string, origin: string) => `${cargo} from ${origin}`,
    unknownOrigin: "elsewhere",
    types: {
      depot: "Depot",
      station: "Station",
      terminal: "Terminal",
    },
    newStationTitle: "New Station",
    type: "Type",
    tapTrackTile: "Tap a straight or dead-end track tile to place a station",
    catchment: "Catchment",
    maxTrainLength: "Max cars",
    storagePerCargo: "Storage",
    monthlyMaintenance: "Upkeep",
    perMonth: "/mo",
    /** PLAN Phase 16: city/station Supplies chips spell out "/ month" plus the cargo's unit word
     * (if any) instead of a bare number, so "42" reads as "42 / month" and "13" as "13 bags /
     * month" — the play-test's "I don't understand the passenger numbers" complaint. */
    supplyRate: (unit: string) => `${unit ? ` ${unit}` : ""} / month`,
    /** PLAN Phase 16: the station panel's "Waiting" line, e.g. "12 passengers waiting". */
    waitingCount: (amount: string) => `${amount} waiting`,
    supplies: "Supplies",
    perMonthNote: "per month",
    tabs: { cargo: "Cargo", trains: "Trains", build: "Build" },
    noDemands: "Accepts nothing yet",
    noSupplies: "Nothing to ship yet",
    accepts: "Demands",
    engineShedFree: "Free Engine Shed",
    waterTowerBuilt: "Water Tower",
    buildWaterTower: "Build Water Tower",
    rename: "Name",
    upgradeToPrefix: "Upgrade to ",
    build: "Build",
    improvements: "Improvements",
    improvementNames: {
      postOffice: "Post Office",
      hotel: "Hotel",
      warehouse: "Warehouse",
      coldStorage: "Cold Storage",
      freightYard: "Freight Yard",
      livestockPens: "Livestock Pens",
    },
    improvementAvailableFrom: (year: number) => `Available from ${year}`,
  },
  trains: {
    buyTitle: "Buy Train",
    locomotive: "Locomotive",
    cars: "Cars",
    orders: "Orders",
    buy: "Buy",
    sell: "Sell",
    sellConfirm: "Tap again to sell",
    sellFor: (refund: string) => `Sell +${refund}?`,
    status: "Status",
    speed: "Speed",
    consist: "Consist",
    empty: "Empty",
    none: "No trains yet.",
    listTitle: "Trains",
    addStop: "+ Add stop (tap a station)",
    tapAStation: "Tap a station on the map…",
    trainsButton: "Trains",
    newBadge: "New!",
    locoTypes: {
      steam: "Steam",
      diesel: "Diesel",
      electric: "Electric",
    },
    statusNames: {
      loading: "Loading",
      moving: "Moving",
      waitingForBlock: "Waiting (block)",
      waitingForStation: "Waiting (station)",
      noRoute: "No route",
      stuck: "Stuck",
      broken: "Broken down",
    },
    loadingRules: {
      auto: "Auto",
      fullLoad: "Full load",
      unloadOnly: "Unload only",
      passThrough: "Pass through",
      /** Unload everything into the Warehouse's transfer stock (PLAN Phase 18 C). */
      transfer: "Unload all (transfer)",
    },
    routeNotElectrified: "Route not electrified",
    /** SPEC §7.5: "the train panel says what they are waiting for." Only shown while `status` is
     * `waitingForBlock`/`waitingForStation` and the train has an actual target to name — falls
     * back to the plain `statusNames` label otherwise (e.g. right after a reroute attempt, before
     * a fresh target is known). */
    waitingForLineClear: (station: string) => `Waiting for line clear to ${station}`,
    waitingForPlatform: (station: string) => `Waiting for platform at ${station}`,
    /** PLAN Phase 18 B: the panel names the blocker, not just the destination. */
    waitingForTrainOnLine: (trains: string, station: string) =>
      `Waiting for ${trains} (single track to ${station})`,
    waitingForTrainAtPlatform: (station: string, trains: string) =>
      `Waiting for platform at ${station} (${trains})`,
    /** Floating label for cargo left at a Warehouse hub (no payment yet). */
    transferred: "Transferred",
    /** Merged floating delivery label ("+$1.9k · 3 deliveries"). */
    deliveriesMerged: (n: number) => `${n} deliveries`,
    noRouteTo: (station: string) => `No route to ${station}`,
    editCars: "Edit cars",
    editCarsTitle: "Edit Consist",
    /** PLAN Phase 15: shown while `train.pendingConsist` is set (the train isn't at a station right
     * now, so the change waits for its next stop). */
    consistChangeQueued: "Changes apply at next station",
    confirm: "Confirm",
    replace: "Replace",
    replaceTitle: "Replace Locomotive",
    tradeInCredit: "Trade-in credit",
    replaceUnavailable: "Cannot pull this train",
    listSubtitle: (n: number) => (n === 1 ? "1 train" : `${n} trains`),
    /** Buy-train wizard (STYLE §11.1). */
    wizard: {
      title: (station: string) => `Buy train · ${station}`,
      steps: { engine: "Engine", cars: "Cars", route: "Route" },
      next: "Next",
      back: "Back",
      stepOf: (n: number, total: number, name: string) => `Step ${n} of ${total} · ${name}`,
      filterAll: "All",
      needsElectrification: "Needs electrified track at this station",
      steamRetired: "Steam can no longer be bought",
      chooseEngine: "Choose an engine",
      introduced: (year: number) => `Since ${year}`,
      carsUsed: (used: number, max: number) => `${used} / ${max} cars`,
      passengerMailOnly: "Passenger and mail cars only",
      noCarsYet: "No cars yet — tap a car below to add it",
      tapToRemove: "Tap a car to remove it",
      suggested: "Suggested",
      applySuggestion: "Use",
      suggestPassengers: "Passengers + mail",
      suggestFreight: (cargo: string) => `${cargo} train`,
      addCar: (name: string) => `Add ${name} car`,
      removeCar: (name: string) => `Remove ${name} car`,
      clear: "Clear",
      stopsHint: "Add at least two stops",
      stopCount: (n: number) => `${n} / 8 stops`,
      yourTrain: "Your train",
    },
    stats: {
      speed: "Top speed",
      power: "Power",
      maxCars: "Max cars",
      reliability: "Reliability",
      price: "Price",
      running: "Running cost",
      perYear: "/yr",
    },
    /** Train panel v2 (STYLE §11.2). */
    panel: {
      tabs: { route: "Route", stats: "Stats" },
      subtitle: (loco: string) => loco,
      moving: (station: string, speed: string) => `To ${station} · ${speed}`,
      loadingAt: (station: string, pct: number) => `Loading at ${station} · ${pct}%`,
      atStop: (station: string) => `At ${station}`,
      hereNow: "Here now",
      nextStop: "Next stop",
      addStop: "Add stop",
      removeStop: "Remove stop",
      moveUp: "Move up",
      moveDown: "Move down",
      changeRule: "Change loading rule",
      earned: "Earned",
      runningCost: "Running cost",
      capacity: "Capacity",
      load: "Load",
      noCars: "No cars",
      loadedOf: (loaded: number, cap: number) => `${loaded} / ${cap} loaded`,
      breakdownChance: (pct: string) => `${pct}% / month breakdown risk`,
      age: "Age",
      ageYears: (n: number) => (n < 1 ? "< 1 yr" : `${n} yr`),
      reliability: "Reliability",
      stopsNeeded: "A train needs at least two stops",
    },
    ruleHint: {
      auto: "Load what is waiting, then go",
      fullLoad: "Wait until every car is full",
      unloadOnly: "Drop cargo, take nothing",
      passThrough: "Roll through without stopping",
      transfer: "Unload into the warehouse",
    },
  },
  /** Short, factual, original notes for the Roster (STYLE §11.3), by locomotive id. */
  locoNotes: {
    "grasshopper-0-4-0":
      "A tiny four-wheeled yard engine with vertical cylinders and a walking-beam drive. Slow and light, it proved that rails could carry paying loads.",
    "planet-2-2-0":
      "Cylinders tucked inside the frame and a single big driving axle made this a smooth, steady runner, and the pattern many early builders copied.",
    "norris-4-2-0":
      "A four-wheel leading truck let this single-driver engine follow sharp, roughly laid curves, opening up hilly country to steam.",
    "american-4-4-0":
      "The 4-4-0 hauled most of the continent's trains in the mid-1800s: four guiding wheels for curves, four drivers for speed.",
    "mogul-2-6-0":
      "Six small drivers gave the Mogul the grip to pull long freight strings up grades where the faster passenger engines slipped.",
    "consolidation-2-8-0":
      "Eight coupled drivers made it the workhorse of heavy freight for half a century: slow, sure-footed and hard to stall.",
    "ten-wheeler-4-6-0":
      "Adding a sixth driver to the American gave more pull at speed, and it became the standard all-round engine of the 1880s.",
    "atlantic-4-4-2":
      "Two large driving wheels and a wide firebox under the cab made it fast, and it reigned on the fastest schedules of its day.",
    "pacific-4-6-2":
      "The trailing truck allowed a big firebox, so the Pacific could sustain high speed with heavy trains. It defined express steam for a generation.",
    "mikado-2-8-2":
      "A trailing truck let the Consolidation's grip be joined to a large firebox, giving the freight engine plenty of steam for long hauls.",
    "hudson-4-6-4":
      "Four-wheel leading and trailing trucks carried a huge boiler at high speed, the last word in fast steam passenger power.",
    "articulated-4-8-8-4":
      "Two sets of eight drivers hinged under a single very long boiler. It was built for the heaviest mountain freight, and it looks the part.",
    "early-electric":
      "Drawing current from an overhead wire or third rail, it needed no smoke or water stops and made tunnels and city approaches far cleaner.",
    "streamliner-diesel":
      "A smooth, wind-cheating nose and a diesel-electric drive gave the 1930s a train that looked like the future and ran like it.",
    "e-unit-electric":
      "A long, smooth-sided electric with an overhead pantograph: quiet, fast and capable of hauling the longest express trains.",
    "cab-unit-diesel":
      "Boxy, streamlined and built to be coupled in sets, the cab unit took over passenger and freight work as steam faded from main lines.",
    "road-switcher-diesel":
      "One short hood with a cab at the end, good to see forward and back. It could shunt in the yard and run the line the same day.",
    "modern-electric":
      "Solid-state controls and a single-arm pantograph give quick acceleration and strong braking, which suits busy suburban timetables.",
    "high-horsepower-diesel":
      "More engine in the same frame: the extra power lets a single locomotive replace a pair on long, heavy freights.",
    "heavy-diesel":
      "A wide-nosed, six-axle diesel built for the heaviest unit trains, prized for steady pulling power rather than top speed.",
    "high-speed-trainset":
      "A fixed set with a wedge nose, powered along its length and built for passengers only. Nothing else on the roster is as fast.",
    "heavy-freight-electric":
      "Wire-fed power and a low centre of gravity: the strongest engine on the roster, made to move mountains of freight.",
  } as Record<string, string>,
  roster: {
    title: "Engine shed",
    subtitle: (owned: number, known: number, total: number) =>
      `${known} of ${total} models known · ${owned} in service`,
    lanes: { steam: "Steam", diesel: "Diesel", electric: "Electric" },
    future: "Not yet built",
    available: "Available",
    retired: "No longer built",
    owned: (n: number) => (n === 0 ? "None in service" : `${n} in service`),
    wheels: "Wheel arrangement",
    introduced: "Introduced",
    detailBack: "Back to roster",
  },
  newEngine: {
    overline: "New locomotive",
    roster: "Roster",
    ok: "OK",
    year: (y: number) => `${y}`,
  },
  finance: {
    title: "Finance",
    subtitle: "Company accounts",
    tabs: { overview: "Overview", year: "This year" },
    noneYet: "Nothing yet",
    cash: "Cash",
    loans: "Loans",
    creditLimit: "Credit",
    borrow: "Borrow",
    repay: "Repay",
    borrowTip: "Borrow $100k",
    repayTip: "Repay $100k",
    creditNote: "Loans come in $100k steps",
    netWorth: "Net worth",
    thisYear: "This year",
    lastYear: "Last year",
    revenue: "Revenue",
    passengers: "Passengers",
    mail: "Mail",
    freight: "Freight",
    expenses: "Expenses",
    trainMaintenance: "Train maint.",
    trackMaintenance: "Track maint.",
    stationMaintenance: "Station maint.",
    breakdownRepairs: "Repairs",
    interest: "Interest",
    construction: "Construction",
    rollingStock: "Rolling stock",
    netProfit: "Net profit",
    operatingProfit: "Operating profit",
    perMonth: "/ month",
    operatingIncome: "Income",
    operatingCosts: "Running costs",
    avg12: (months: number) => (months >= 12 ? "12-month average" : `${months}-month average`),
    last30: "Last 30 days",
    investments: "Investments",
    investmentsNote: "track, stations, trains — not in operating profit",
    investmentLabel: (label: string) => `${label} (investment)`,
    chartTitle: "Cash & net worth",
    chartCash: "Cash",
    chartNetWorth: "Net worth",
    yearlyReport: "Yearly Report",
    bankruptWarning: "Cash has been negative for months — borrow, sell trains, or cut costs.",
  },
  yearlyReport: {
    title: (year: number) => `${year} Year in Review`,
    close: "Close",
    newTechnology: "New technology",
  },
  news: {
    title: "News",
    button: "News",
    empty: "No news yet.",
    kinds: {
      newLocomotive: (locoName: string) => `New locomotive available: ${locoName}`,
      breakdown: (trainName: string) => `${trainName} has broken down and is being repaired`,
      washout: (nearName: string) => `A wooden bridge near ${nearName} has washed out`,
      trafficJam: (nearName: string) =>
        `Traffic jam near ${nearName} — consider double track or more stations`,
      noRoute: (trainName: string, stationName: string) =>
        `${trainName} has no route to ${stationName}`,
      cityGrowth: (cityName: string, tierName: string) =>
        `${cityName} has grown into a ${tierName}!`,
      civicInvestment: (cityName: string) => `Civic Investment boosts growth in ${cityName}`,
      cityFounded: (cityName: string) => `${cityName} has been founded!`,
      goalCompleted: (tierName: string, description: string) =>
        `${tierName} goal reached: ${description}`,
    },
  },
  goals: {
    title: "Goals",
    button: "Goals",
    tierNames: {
      bronze: "Bronze",
      silver: "Silver",
      gold: "Gold",
    },
    complete: "Complete",
    overdue: "Overdue",
    byYear: (year: number) => `By ${year}`,
    none: "This map has no goals.",
    doneCount: (done: number, total: number) => `${done} of ${total} reached`,
    types: {
      connect: (cities: string) => `Connect ${cities} by rail`,
      annualRevenue: (amount: string) => `Annual revenue ${amount}`,
      netWorth: (amount: string) => `Net worth ${amount}`,
      cityTier: (city: string, tier: string) => `${city} reaches ${tier}`,
      delivered: (amount: number, cargo: string) =>
        `Deliver ${amount} carloads of ${cargo} in a year`,
      electrifiedTiles: (n: number) => `Electrify ${n} tiles`,
    },
  },
  celebration: {
    title: "Goal reached!",
    close: "Continue",
  },
  titleScreen: {
    gameTitle: "Railroads",
    newGame: "New Game",
    continue: "Continue",
    loadGame: "Load Game",
    settings: "Settings",
  },
  settings: {
    title: "Settings",
    groupPlay: "Gameplay",
    groupDisplay: "Display & sound",
    units: "Speed units",
    unitsNames: { kmh: "km/h", mph: "mph" },
    quickBuild: "Quick build",
    quickBuildDesc: "Skip the confirm bar — releasing a drag builds immediately",
    sound: "Sound",
    soundDesc: "Whistle, chug and cash-register sound effects",
    grid: "Show tile grid",
    uiScale: "UI scale",
    uiScaleNames: { "0.85": "Small", "1": "Normal", "1.15": "Large" },
  },
  saveLoad: {
    loadTitle: "Load Game",
    saveTitle: "Save Game",
    autosaveLabel: (n: number) => `Autosave ${n}`,
    emptySlot: "Empty slot",
    load: "Load",
    save: "Save",
    overwrite: "Overwrite",
    delete: "Delete",
    deleteConfirm: "Delete this save?",
    oldMapScale: "This save uses the old map scale and can't be loaded",
    namePrompt: "Save name",
    nameDefault: "My Game",
  },
  hints: {
    steps: [
      "Drag on the map with the Track tool to lay your first line.",
      "Tap Station on a straight piece of track or a dead end to build a station.",
      "Buy a train at a station with an Engine Shed (the first station you build gets one free).",
      "Set orders — tap stations on the map — then watch the cash roll in as it delivers cargo.",
    ] as string[],
    next: "Got it",
    done: "Start playing",
    skip: "Skip tips",
  },
  newGame: {
    title: "New Game",
    tabRealWorld: "Real World",
    tabRandom: "Random",
    startYear: "Start year",
    difficulty: "Difficulty",
    difficultyNames: {
      easy: "Easy",
      normal: "Normal",
      hard: "Hard",
    },
    startingCash: "Starting cash",
    start: "Start Game",
    seed: "Seed",
    randomizeSeed: "Randomize seed",
    size: "Map size",
    sizeNames: {
      small: "Small",
      medium: "Medium",
      large: "Large",
    },
    waterLevel: "Water level",
    waterLevelNames: {
      low: "Low",
      normal: "Normal",
      high: "High",
    },
    roughness: "Terrain",
    roughnessNames: {
      flat: "Flat",
      normal: "Normal",
      mountainous: "Mountainous",
    },
    cityCount: "Cities",
    cityCountNames: {
      few: "Few",
      normal: "Normal",
      many: "Many",
    },
    resourceDensity: "Resources",
    resourceDensityNames: {
      low: "Low",
      normal: "Normal",
      high: "High",
    },
    regionDescriptions: {
      "us-east": "Coastlines, the Appalachians, and the industrial Northeast.",
      gb: "London to Glasgow — Great Britain's first railway age.",
      "central-eu": "The Alps divide Italy from Germany and Austria.",
      "us-west": "Deserts, the Rockies, and the Pacific coast.",
    } as Record<string, string>,
  },
  debug: {
    regenerate: "New seed",
    seedLabel: "Seed",
    sizeLabel: "Size",
    sizeSmall: "Small",
    sizeMedium: "Medium",
    sizeLarge: "Large",
  },
  errorBoundary: {
    title: "Something went wrong",
    body: "Railroads hit an unexpected error. Your progress has been saved to a recovery slot — reload and use Load Game to pick it up.",
    reload: "Save & Reload",
  },
};
