/** Generates docs/BALANCE.md. Skipped unless BALANCE_REPORT=1:
 *   BALANCE_REPORT=1 npx vitest run tests/sim/balanceReport.test.ts */
import { writeFileSync } from "node:fs";
import { describe, it } from "vitest";
import { CITY_TIER_DEFS } from "../../src/data/cities";
import { CARGO } from "../../src/data/cargo";
import { citySupply } from "../../src/sim/economy/cityStats";
import { measureRoute, type RouteSpec } from "./balanceRoutes";
import type { City } from "../../src/sim/economy/types";

const ERAS: Array<{ year: number; loco: string }> = [
  { year: 1830, loco: "grasshopper-0-4-0" },
  { year: 1860, loco: "american-4-4-0" },
  { year: 1900, loco: "atlantic-4-4-2" },
  { year: 1950, loco: "road-switcher-diesel" },
];
const KMS = [50, 100, 200];

const k = (n: number): string => `${Math.round(n / 1000)}k`;

describe.runIf(process.env.BALANCE_REPORT === "1")("balance report", () => {
  it("writes docs/BALANCE.md", { timeout: 600_000 }, () => {
    const out: string[] = ["# Balance report (generated)", ""];
    out.push("Generated by `BALANCE_REPORT=1 npx vitest run tests/sim/balanceReport.test.ts`.");
    out.push(
      "One straight route on a plain map, Normal difficulty, year-3 ledger (revenue / net profit per train-year,",
    );
    out.push(
      "track/station upkeep included). Consist = min(loco max cars, 8). Cells: `revenue / profit`.",
    );
    out.push("");
    out.push("## City supply (per month, fully covered)");
    out.push("");
    out.push("| Pop | Passengers | = cars | Mail | = cars |", "|---|---|---|---|---|");
    for (const [tier, pop] of [
      ["village", 3_000],
      ["town", 12_000],
      ["town", 18_000],
      ["city", 40_000],
      ["city", 100_000],
      ["metropolis", 250_000],
    ] as const) {
      const s = citySupply({ population: pop, tier } as City);
      out.push(
        `| ${tier} ${pop} | ${s.passengers} | ${(s.passengers / CARGO.passengers.capacity).toFixed(1)} | ${s.mail} | ${(s.mail / CARGO.mail.capacity).toFixed(1)} |`,
      );
    }
    out.push("");
    void CITY_TIER_DEFS;
    const specs: Array<{
      label: string;
      make: (km: number, e: (typeof ERAS)[number]) => RouteSpec;
    }> = [
      {
        label: "Coal (mine → steel mill)",
        make: (km, e) => ({ cargo: "coal", km, ...e, producer: "coalMine", acceptor: "steelMill" }),
      },
      {
        label: "Grain (farm → food plant)",
        make: (km, e) => ({ cargo: "grain", km, ...e, producer: "farm", acceptor: "foodPlant" }),
      },
      {
        label: "Wood (logging camp → sawmill)",
        make: (km, e) => ({
          cargo: "wood",
          km,
          ...e,
          producer: "loggingCamp",
          acceptor: "sawmill",
        }),
      },
      {
        label: "Passengers Town 12k ↔ Town 12k",
        make: (km, e) => ({ cargo: "passengers", km, ...e, population: 12_000, tier: "town" }),
      },
      {
        label: "Passengers City 40k ↔ City 40k",
        make: (km, e) => ({ cargo: "passengers", km, ...e, population: 40_000, tier: "city" }),
      },
      {
        label: "Mail Town 12k ↔ Town 12k",
        make: (km, e) => ({ cargo: "mail", km, ...e, population: 12_000, tier: "town" }),
      },
      {
        label: "Mail City 40k ↔ City 40k",
        make: (km, e) => ({ cargo: "mail", km, ...e, population: 40_000, tier: "city" }),
      },
    ];
    for (const spec of specs) {
      out.push(`## ${spec.label}`, "");
      out.push("| Era / loco | cars | " + KMS.map((x) => `${x} km`).join(" | ") + " |");
      out.push("|---|---|" + KMS.map(() => "---").join("|") + "|");
      for (const e of ERAS) {
        const cells: string[] = [];
        let cars = 0;
        for (const km of KMS) {
          try {
            const r = measureRoute(spec.make(km, e));
            cars = r.cars;
            cells.push(`${k(r.revenue)} / ${k(r.profit)}`);
          } catch (err) {
            cells.push(`n/a (${(err as Error).message.slice(0, 30)})`);
          }
        }
        out.push(`| ${e.year} ${e.loco} | ${cars} | ${cells.join(" | ")} |`);
      }
      out.push("");
    }
    writeFileSync("docs/BALANCE.md", out.join("\n"));
  });
});
