/** Generates docs/BALANCE.md. Skipped unless BALANCE_REPORT=1:
 *   BALANCE_REPORT=1 npx vitest run tests/sim/balanceReport.test.ts */
import { writeFileSync } from "node:fs";
import { describe, it } from "vitest";
import { CITY_TIER_DEFS } from "../../src/data/cities";
import { CARGO } from "../../src/data/cargo";
import { citySupply } from "../../src/sim/economy/cityStats";
import { measureMean, measureRoute, type RouteSpec } from "./balanceRoutes";
import type { City } from "../../src/sim/economy/types";

const ERAS: Array<{ year: number; loco: string }> = [
  { year: 1830, loco: "grasshopper-0-4-0" },
  { year: 1860, loco: "american-4-4-0" },
  { year: 1900, loco: "atlantic-4-4-2" },
  { year: 1950, loco: "road-switcher-diesel" },
];
/** The key table (Economic model v2): one row per era with the locomotive a player would buy then. */
const KEY_ERAS: Array<{ year: number; loco: string }> = [
  { year: 1830, loco: "grasshopper-0-4-0" },
  { year: 1840, loco: "norris-4-2-0" },
  { year: 1860, loco: "american-4-4-0" },
  { year: 1900, loco: "atlantic-4-4-2" },
  { year: 1920, loco: "pacific-4-6-2" },
  { year: 1950, loco: "road-switcher-diesel" },
  { year: 1980, loco: "heavy-diesel" },
];

const pct = (n: number): string => `${Math.round(n * 100)}%`;

/** ROI and cost structure per era (see SPEC §9 "Economic model v2" for the targets). */
function keyTables(): string[] {
  const out: string[] = [];
  const routes: Array<{ label: string; make: (e: (typeof KEY_ERAS)[number]) => RouteSpec }> = [
    {
      label: "Passengers Town 12k ↔ Town 12k, 50 km",
      make: (e) => ({ cargo: "passengers", km: 50, ...e, population: 12_000, tier: "town" }),
    },
    {
      label: "Passengers City 40k ↔ City 40k, 100 km",
      make: (e) => ({ cargo: "passengers", km: 100, ...e, population: 40_000, tier: "city" }),
    },
    {
      label: "Passengers Metropolis 250k ↔ City 100k, 100 km (a rich route)",
      make: (e) => ({
        cargo: "passengers",
        km: 100,
        ...e,
        population: 150_000,
        tier: "metropolis",
      }),
    },
    {
      label: "Coal mine → steel mill, 100 km",
      make: (e) => ({ cargo: "coal", km: 100, ...e, producer: "coalMine", acceptor: "steelMill" }),
    },
  ];
  out.push("## Key table: revenue / net profit per train-year (return on the train's price)", "");
  out.push(
    "Normal difficulty, year-3 ledger, mean of 3 seeds. `ROI` = net profit ÷ price of locomotive + cars.",
    "",
  );
  for (const route of routes) {
    out.push(`### ${route.label}`, "");
    out.push("| Era / loco | price | revenue | profit | ROI |", "|---|---|---|---|---|");
    for (const e of KEY_ERAS) {
      try {
        const a = measureMean(route.make(e));
        out.push(
          `| ${e.year} ${e.loco} | ${k(a.price)} | ${k(a.revenue)} | ${k(a.profit)} | ${pct(a.profit / a.price)} |`,
        );
      } catch (err) {
        out.push(`| ${e.year} ${e.loco} | n/a (${(err as Error).message.slice(0, 40)}) | | | |`);
      }
    }
    out.push("");
  }
  out.push(
    "### Hard vs Normal: Passengers City 40k ↔ City 40k, 100 km (profit per train-year)",
    "",
  );
  out.push("| Era | Normal | Hard | Hard ÷ Normal |", "|---|---|---|---|");
  for (const e of KEY_ERAS) {
    const base = {
      cargo: "passengers" as const,
      km: 100,
      ...e,
      population: 40_000,
      tier: "city" as const,
    };
    const normal = measureMean(base);
    const hard = measureMean({ ...base, difficulty: "hard" });
    out.push(
      `| ${e.year} | ${k(normal.profit)} | ${k(hard.profit)} | ${pct(hard.profit / normal.profit)} |`,
    );
  }
  out.push("");
  out.push(
    "### Where the money goes: Passengers City 40k ↔ City 40k, 100 km (share of revenue)",
    "",
  );
  const cols = [
    ["trainMaintenance", "fuel & servicing"],
    ["crewWages", "crew"],
    ["trackMaintenance", "track"],
    ["trackWear", "wear"],
    ["stationMaintenance", "stations"],
    ["breakdownRepairs", "repairs"],
    ["propertyTax", "property tax"],
    ["incomeTax", "income tax"],
  ] as const;
  out.push(
    "| Era | revenue | " + cols.map(([, l]) => l).join(" | ") + " |",
    "|---|---|" + cols.map(() => "---").join("|") + "|",
  );
  for (const e of KEY_ERAS) {
    const a = measureMean({
      cargo: "passengers",
      km: 100,
      ...e,
      population: 40_000,
      tier: "city",
    });
    out.push(
      `| ${e.year} | ${k(a.revenue)} | ${cols.map(([key]) => pct((a.ledger[key as keyof typeof a.ledger] ?? 0) / Math.max(1, a.revenue))).join(" | ")} |`,
    );
  }
  out.push("");
  return out;
}
const KMS = [50, 100, 200];

const k = (n: number): string => `${Math.round(n / 1000)}k`;

describe.runIf(process.env.BALANCE_REPORT === "1")("balance report", () => {
  it("writes docs/BALANCE.md", { timeout: 600_000 }, () => {
    const out: string[] = ["# Balance report (generated)", ""];
    out.push("Generated by `BALANCE_REPORT=1 npx vitest run tests/sim/balanceReport.test.ts`.");
    out.push(
      "One straight route on a plain map, Normal difficulty, year-3 ledger (revenue / net profit per train-year,",
    );
    out.push(
      "track/station upkeep included). Consist = min(loco max cars, 8). Cells: `revenue / profit`.",
    );
    out.push("");
    out.push(
      "**Targets** (Economic model v2, SPEC §9.5b; asserted in `tests/sim/economy/economicModel.test.ts` and `balanceEarly.test.ts`):",
      "- a Norris on a 10-tile (50 km) Town↔Town line returns ≥ 25 % of its price a year;",
      "- a Grasshopper on a short line at least breaks even;",
      "- repairs < 10 % of revenue in every era with an Engine Shed at each end;",
      "- a rich route (250k ↔ 150k cities, 100 km) earns ≤ ~3.3× the train's price a year after tax and wear from 1900 on;",
      "- Hard is clearly harder than Normal (heavier tax schedule, higher interest, dearer building, more breakdowns).",
      "",
      "Earlier versions of this file (before Phase 28A) are in git history and in the Phase 28A entry of PROGRESS.md.",
    );
    out.push("");
    out.push(...keyTables());
    if (process.env.BALANCE_KEY_ONLY === "1") {
      writeFileSync(process.env.BALANCE_OUT ?? "docs/BALANCE.md", out.join("\n"));
      return;
    }
    out.push("## City supply (per month, fully covered)");
    out.push("");
    out.push("| Pop | Passengers | = cars | Mail | = cars |", "|---|---|---|---|---|");
    for (const [tier, pop] of [
      ["village", 3_000],
      ["town", 12_000],
      ["town", 18_000],
      ["city", 40_000],
      ["city", 100_000],
      ["metropolis", 250_000],
    ] as const) {
      const s = citySupply({ population: pop, tier } as City);
      out.push(
        `| ${tier} ${pop} | ${s.passengers} | ${(s.passengers / CARGO.passengers.capacity).toFixed(1)} | ${s.mail} | ${(s.mail / CARGO.mail.capacity).toFixed(1)} |`,
      );
    }
    out.push("");
    void CITY_TIER_DEFS;
    const specs: Array<{
      label: string;
      make: (km: number, e: (typeof ERAS)[number]) => RouteSpec;
    }> = [
      {
        label: "Coal (mine → steel mill)",
        make: (km, e) => ({ cargo: "coal", km, ...e, producer: "coalMine", acceptor: "steelMill" }),
      },
      {
        label: "Grain (farm → food plant)",
        make: (km, e) => ({ cargo: "grain", km, ...e, producer: "farm", acceptor: "foodPlant" }),
      },
      {
        label: "Wood (logging camp → sawmill)",
        make: (km, e) => ({
          cargo: "wood",
          km,
          ...e,
          producer: "loggingCamp",
          acceptor: "sawmill",
        }),
      },
      {
        label: "Passengers Town 12k ↔ Town 12k",
        make: (km, e) => ({ cargo: "passengers", km, ...e, population: 12_000, tier: "town" }),
      },
      {
        label: "Passengers City 40k ↔ City 40k",
        make: (km, e) => ({ cargo: "passengers", km, ...e, population: 40_000, tier: "city" }),
      },
      {
        label: "Mail Town 12k ↔ Town 12k",
        make: (km, e) => ({ cargo: "mail", km, ...e, population: 12_000, tier: "town" }),
      },
      {
        label: "Mail City 40k ↔ City 40k",
        make: (km, e) => ({ cargo: "mail", km, ...e, population: 40_000, tier: "city" }),
      },
    ];
    for (const spec of specs) {
      out.push(`## ${spec.label}`, "");
      out.push("| Era / loco | cars | " + KMS.map((x) => `${x} km`).join(" | ") + " |");
      out.push("|---|---|" + KMS.map(() => "---").join("|") + "|");
      for (const e of ERAS) {
        const cells: string[] = [];
        let cars = 0;
        for (const km of KMS) {
          try {
            const r = measureRoute(spec.make(km, e));
            cars = r.cars;
            cells.push(`${k(r.revenue)} / ${k(r.profit)}`);
          } catch (err) {
            cells.push(`n/a (${(err as Error).message.slice(0, 30)})`);
          }
        }
        out.push(`| ${e.year} ${e.loco} | ${cars} | ${cells.join(" | ")} |`);
      }
      out.push("");
    }
    writeFileSync("docs/BALANCE.md", out.join("\n"));
  });
});
