/** Registry of committed real-world regions (SPEC §4.3). Each entry is added here once its region
 * JSON has been generated by `tools/mapgen` (see docs/PLAN.md Phase 10 — regions land one at a time). */
import usEast from "../../data/regions/us-east.json";
import type { RegionId, RegionJson } from "./types";

export { REGION_IDS, type RegionId } from "./types";
export { loadRegion, type LoadedRegion, type PendingCityFounding } from "./load";

export const REGIONS: Partial<Record<RegionId, RegionJson>> = {
  "us-east": usEast as RegionJson,
};

export function getRegion(id: RegionId): RegionJson {
  const region = REGIONS[id];
  if (!region) throw new Error(`region not available yet: ${id}`);
  return region;
}
